namespace TwinCAT.Ads
{
    using System;
    using System.ComponentModel;

    public enum AdsErrorCode
    {
        NoError = 0,
        InternalError = 1,
        NoRTime = 2,
        LockedMemoryError = 3,
        MailBoxError = 4,
        WrongHMsg = 5,
        TargetPortNotFound = 6,
        TargetMachineNotFound = 7,
        UnknownCommandID = 8,
        BadTaskID = 9,
        NoIO = 10,
        UnknwonAmsCommand = 11,
        Win32Error = 12,
        PortNotConnected = 13,
        InvalidAmsLength = 14,
        InvalidAmsNetID = 15,
        LowInstallLevel = 0x10,
        NoDebug = 0x11,
        PortDisabled = 0x12,
        PortConnected = 0x13,
        AmsSyncWin32Error = 20,
        SyncTimeOut = 0x15,
        AmsSyncAmsError = 0x16,
        AmsSyncNoIndexMap = 0x17,
        InvalidAmsPort = 0x18,
        NoMemory = 0x19,
        TCPSendError = 0x1a,
        HostUnreachable = 0x1b,
        AmsInvalidFragment = 0x1c,
        NoLockedMemory = 0x500,
        ResizeMemory = 0x501,
        MailboxFull = 0x502,
        DebugBoxFull = 0x503,
        UnknownPortType = 0x504,
        RouterNotInitialized = 0x505,
        PortAlreadyInUse = 0x506,
        PortNotRegistered = 0x507,
        NoMoreQueues = 0x508,
        InvalidPort = 0x509,
        RouterNotActive = 0x50a,
        DeviceError = 0x700,
        DeviceServiceNotSupported = 0x701,
        DeviceInvalidGroup = 0x702,
        DeviceInvalidOffset = 0x703,
        DeviceInvalidAccess = 0x704,
        DeviceInvalidSize = 0x705,
        DeviceInvalidData = 0x706,
        DeviceNotReady = 0x707,
        DeviceBusy = 0x708,
        DeviceInvalidContext = 0x709,
        DeviceNoMemory = 0x70a,
        DeviceInvalidParam = 0x70b,
        [EditorBrowsable((EditorBrowsableState) EditorBrowsableState.Never), Obsolete("Use 'DeviceInvalidParam instead!")]
        DeviceInavlidParam = 0x70b,
        DeviceNotFound = 0x70c,
        DeviceSyntaxError = 0x70d,
        DeviceIncompatible = 0x70e,
        DeviceExists = 0x70f,
        DeviceSymbolNotFound = 0x710,
        DeviceSymbolVersionInvalid = 0x711,
        DeviceInvalidState = 0x712,
        DeviceTransModeNotSupported = 0x713,
        DeviceNotifyHandleInvalid = 0x714,
        DeviceClientUnknown = 0x715,
        DeviceNoMoreHandles = 0x716,
        DeviceInvalidWatchsize = 0x717,
        DeviceNotInitialized = 0x718,
        DeviceTimeOut = 0x719,
        DeviceNoInterface = 0x71a,
        DeviceInvalidInterface = 0x71b,
        DeviceInvalidCLSID = 0x71c,
        DeviceInvalidObjectID = 0x71d,
        DeviceRequestIsPending = 0x71e,
        DeviceRequestIsAborted = 0x71f,
        DeviceSignalWarning = 0x720,
        DeviceInvalidArrayIndex = 0x721,
        DeviceSymbolNotActive = 0x722,
        DeviceAccessDenied = 0x723,
        [EditorBrowsable((EditorBrowsableState) EditorBrowsableState.Never), Obsolete("Use 'DeviceLicenseNotFound instead!", false)]
        DeviceMissingLicense = 0x724,
        DeviceLicenseNotFound = 0x724,
        DeviceLicenseExpired = 0x725,
        DeviceLicenseExceeded = 0x726,
        DeviceLicenseInvalid = 0x727,
        DeviceLicenseSystemId = 0x728,
        DeviceLicenseNoTimeLimit = 0x729,
        DeviceLicenseFutureIssue = 0x72a,
        DeviceLicenseTimeToLong = 0x72b,
        [EditorBrowsable((EditorBrowsableState) EditorBrowsableState.Never), Obsolete("Use 'DeviceException instead!", false)]
        DeviceExceptionDuringStartup = 0x72c,
        DeviceException = 0x72c,
        DeviceLicenseDuplicated = 0x72d,
        DeviceSignatureInvalid = 0x72e,
        DeviceCertificateInvalid = 0x72f,
        DeviceLicenseOemNotFound = 0x730,
        DeviceLicenseRestricted = 0x731,
        DeviceLicenseDemoDenied = 0x732,
        DeviceInvalidFncId = 0x733,
        DeviceOutOfRange = 0x734,
        DeviceInvalidAlignment = 0x735,
        DeviceLicensePlatform = 0x736,
        ClientError = 0x740,
        ClientInvalidParameter = 0x741,
        ClientListEmpty = 0x742,
        [Obsolete("Use ClientVariableInUse instead"), EditorBrowsable((EditorBrowsableState) EditorBrowsableState.Never)]
        ClientVaraiableInUse = 0x743,
        ClientVariableInUse = 0x743,
        ClientDuplicateInvokeID = 0x744,
        ClientSyncTimeOut = 0x745,
        ClientW32OR = 0x746,
        ClientTimeoutInvalid = 0x747,
        ClientPortNotOpen = 0x748,
        ClientNoAmsAddr = 0x749,
        ClientSyncInternal = 0x750,
        ClientAddHash = 0x751,
        ClientRemoveHash = 0x752,
        ClientNoMoreSymbols = 0x753,
        ClientSyncResInvalid = 0x754,
        ClientSyncPortLocked = 0x755,
        ClientQueueFull = 0x8000,
        WSA_ConnRefused = 0x274d
    }
}

